version: '3.1'

services:

  flask:
    build:
      context: .
      dockerfile: flask.Dockerfile
    command: gunicorn -w 4 --bind 0.0.0.0:5000 wsgi:app
    env_file:
      - ./.env.docker
    volumes:
      - .:/usr/src/app
      - ./.env.development:/usr/src/flask/.env # m'asseguro que el .env.development es el es fa servir
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2
    restart: no
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: patata
      POSTGRES_DB: userdb
      PDDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - postgres_volume:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1
    ports:
      - 127.0.0.1:8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - 127.0.0.1:5000:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wannapop/static:/usr/src/app/wannapop/static
    depends_on:
      - flask

volumes:
  postgres_volume: