version: '3.1'

services:

  postgres:
    image: postgres:16.2
    restart: no
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: patata
      POSTGRES_DB: userdb
      PDDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  adminer:
    image: adminer:4.8.1
    ports:
      - 127.0.0.1:8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

volumes:
  postgres_volume: